### ISSUE TITLE
Project is not inside packagist

### ISSUE THREAD

**Issue by neilferreira** [theodo/TheodoRogerCmsBundle#36]
Hi,

I can't find this project inside packagist,  you've got a composer.json file in the project but that name hasn't been registered,  any chance you can create it?

cheers

**Comment by benja-M-1** [comment]
Hi I have created it : http://packagist.org/packages/theodo/roger-cms-bundle, you can use it with composer now :)

Let us know if you have any trouble to use it.

**Comment by marekkalnik** [comment]
There are some problems with symfony master compability, we're dropping user management. Should be stable in few days.

**Comment by neilferreira** [comment]
I will check back in a few days,  I've just started running through it, firstly all of the fixtures were missing the created/updated timestamp, which I assume you're going to do through doctrine pre/post persist methods rather than having the user specify these values.

And like you said, the user management is fairly broken,  please ping me when you have had chance to look at it,  I'll fire it up again.

Probably worth it for you to fork the current symfony-standard master repository, add your composer deps and everything else you need to get the project fired up and call it your sandbox, that way someone can easily get their project running in 5mins by just doing a git clone && composer update.

Cheers

**Comment by marekkalnik** [comment]
The fixtures are missing timestampable behavior, you need to enable it. Take a look at config sample in resources/config.
