### ISSUE TITLE
Fatal error: Declaration of Theodo\RogerCmsBundle\Form\PageType::buildForm()

### ISSUE THREAD

**Issue by NaGeL182** [theodo/TheodoRogerCmsBundle#59]
I installed the bundle to a new Symfony 2 without vendors 2.0.15 using the vendor script
everything went fine created security to get access to the admin page.

but when i tried to access:
/admin/pages/homepage/new

the folowing error ocured.

Fatal error: Declaration of Theodo\RogerCmsBundle\Form\PageType::buildForm() must be compatible with that of Symfony\Component\Form\FormTypeInterface::buildForm() in /var/www/Symfony/vendor/bundles/Theodo/RogerCmsBundle/Form/PageType.php on line 12

**Comment by marekkalnik** [comment]
Thank you for submitting the issue, I'll look into it.

**Comment by marekkalnik** [comment]
Hi,

Seems like there's an error in our documentation and you've downloaded the symfony 2.1 version.

I've updated the installation istructions.

**Comment by NaGeL182** [comment]
If the vendor script updates symfony 2.1 than yes, you are correct.

If not, then  that cant be the problem because i downloaded the zip with vendors from the symfony website and used that.

**Comment by marekkalnik** [comment]
Sorry, I've messed up the wording... You've downloaded the version for symfony 2.1 (the master branch) rather than the 2.0.x branch.

**Comment by NaGeL182** [comment]
Sorry, but I'm pretty sure i used this link : http://symfony.com/download?v=Symfony_Standard_Vendors_2.0.15.zip
to download symfony, so unless the vendor scripts update the symfony core bundles, or i might have screwed up something during the installation( clean symfony using that link, than adding the lines to the deps file than running the vendor script.)  it can't be symfony 2.1

**Comment by marekkalnik** [comment]
The RogerCmsBundle has two versions - the master branch, which follows symfony 2.1 development and the sf2.0.x branch that works with symfony 2.0. I've updated the installation documentation in sf2.0.x branch, so you can just copy-paste the deps entries. In short - you need to fix the RogerCmsBundle version to sf2.0.x in your deps.

**Comment by NaGeL182** [comment]
thank you for the clarification.

**Comment by marekkalnik** [comment]
You're welcome.
