### ISSUE TITLE
Required ACL Roles for admin access

### ISSUE THREAD

**Issue by vamsiikrishna** [theodo/TheodoRogerCmsBundle#70]
Hi,
I am trying to setup RogerCms  along with FOSUserBundle.
what are the permissions required to access Admin Panel ?

Regards

**Comment by benja-M-1** [comment]
According to https://github.com/theodo/TheodoRogerCmsBundle/blob/master/Controller/Backend/PageController.php#L38 you should have the ROLE_ROGER_READ_CONTENT role.

You can find the list of every roles in the `security.yml` file in the fixtures of the tests : https://github.com/theodo/TheodoRogerCmsBundle/blob/master/Tests/Fixtures/app/config/security.yml
