### ISSUE TITLE
Variable "app" does not exist

### ISSUE THREAD

**Issue by ivoba** [theodo/TheodoRogerCmsBundle#71]
I dont know if thats a issue of yours but maybe you can give a hint.

I try to extend a template that is in another bundle, i do so by simply creating a template in which is nothing but an extend command:

```
{% extends 'MyBundle::layout.html.twig' %}
```

which again extends to base

```
{% extends 'MyBundle::base.html.twig' %}
```

This works so far.

But as soon as i try to call a global twig var like `app.session` in base i get the error:

```
Variable "app" does not exist
```

Through a normal controller this works.
Any ideas where i can have a look?

**Comment by marekkalnik** [comment]
@ivoba Looks like a roger.templating issue. I guess the twig is not injected with correct symfony context. I'll take a look at it in the evening.

**Comment by marekkalnik** [comment]
Ok, I've found the bug, seems like the way of injecting global variables has changed. I'll be pushing a fix soon.

**Comment by marekkalnik** [comment]
@ivoba Hi, I've fixed the bug. Could you download the master version and confirm that it's ok in your project?

**Comment by ivoba** [comment]
Yes it works now.
Thank you

**Comment by marekkalnik** [comment]
Great! Thanks for reporting this. I've pushed a tag - v0.6.1 - if you prefer to put a tag over dev-master in your composer.json.
